spring:
  client:
    serviceUrl:
      defaultZone: http://localhost:9998/eureka/
  cloud:
    gateway:
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*) , /${path}
        - id: microservice-projet
          uri: lb://microservice-projet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*) , /${path}
